### ISSUE TITLE
Exeption bei Eingabe

### ISSUE THREAD

**Issue by pferdausglas** [bodenaaron/GeomFigur#5]
Wenn man bei der Eingabe von Werten die die Form beschreiben nichts eintippt hängt das Programm.

**Comment by pferdausglas** [comment]
oder eben bei nicht Buchstaben und co.

**Comment by pferdausglas** [comment]
Glaube es wäre am besten diese Eingabe einfach zu ignorieren.

**Comment by bodenaaron** [comment]
Die oberen Menüs sind gemacht, fehlt nur noch die cm angaben
